frontend/src/App.jsx, frontend/src/components/Layout/AdminLayout/AdminLayout.jsx, frontend/src/pages/AdminExercisePage/AdminExercisePage.jsx, frontend/src/pages/AdminFeedPage/AdminFeedPage.jsx, frontend/src/pages/AdminFoodPage/AdminFoodPage.jsx, frontend/src/routes/AppRouter.jsx
=> feat/ 어드민 페이지 생성

backend/Model/DailyExercise.js, backend/Model/DailyFood.js, backend/Model/DailyWater.js, backend/Model/DailyWeight.js, backend/Model/Exercise.js, backend/Model/Feed.js, backend/Model/Food.js, backend/app.js, backend/controllers/authController.js, backend/controllers/exerciseController.js, backend/controllers/feedController.js, backend/controllers/foodController.js, backend/controllers/user.controller.js, backend/routes/apiRouter.js, backend/routes/authRouter.js, backend/routes/exerciseRouter.js, backend/routes/feedRouter.js, backend/routes/foodRouter.js, backend/routes/userRouter.js, frontend/.env, frontend/package-lock.json, frontend/package.json, frontend/src/utils/api.jsx
api.jsx 파일 생성
Backend Model 생성
Backend Router 생성
Backend Controller 생성
=> feat: Backend Setting

frontend/src/App.jsx, frontend/src/components/shared/NavBar/NavBar.css, frontend/src/components/shared/NavBar/NavBar.jsx, frontend/src/reset.css
- NavBar 구현했습니다.
- a태그 방문했던 것 보라색으로 바뀌지 않도록 했습니다. 
- a태그 focus시 점선나오는 것 제거했습니다.
- path가 포함된 모든 페이지에서 NavBar item이 활성화되도록 수정했습니다.
=> feat: NavBar 구현

frontend/src/components/Admin/AdminTable/AdminTable.css, frontend/src/components/Admin/AdminTable/AdminTable.jsx, frontend/src/components/Layout/AdminLayout/AdminLayout.css, frontend/src/components/Layout/AdminLayout/AdminLayout.jsx, frontend/src/components/Layout/AdminLayout/components/AdminHeader/AdminHeader.css, frontend/src/components/Layout/AdminLayout/components/AdminHeader/AdminHeader.jsx, frontend/src/components/Layout/AdminLayout/components/AdminNavbar/AdminNavbar.css, frontend/src/components/Layout/AdminLayout/components/AdminNavbar/AdminNavbar.jsx, frontend/src/components/shared/AddButton/AddButton.css, frontend/src/components/shared/AddButton/AddButton.jsx, frontend/src/components/shared/BottomSheet/BottomSheet.css, frontend/src/components/shared/BottomSheet/BottomSheet.jsx, frontend/src/components/shared/BottomSheet/components/useBottomSheet.jsx, frontend/src/components/shared/CategorieInput/CategorieInput.css, frontend/src/components/shared/CategorieInput/CategorieInput.jsx, frontend/src/components/shared/FormInput/FormInput.css, frontend/src/components/shared/FormInput/FormInput.jsx, frontend/src/components/shared/PageNationBar/PageNationBar.css, frontend/src/components/shared/PageNationBar/PageNationBar.jsx, frontend/src/components/shared/SearchBar/SearchBar.css, frontend/src/components/shared/SearchBar/SearchBar.jsx, frontend/src/core/utils/fn/urlParser.js, frontend/src/index.css, frontend/src/pages/AdminFoodPage/AdminFoodPage.jsx, frontend/src/pages/AdminFoodPage/components/AdminFoodAddForm/AdminFoodAddForm.jsx, frontend/src/pages/AdminFoodPage/components/AdminFoodDeleteForm/AdminFoodDeleteForm.jsx, frontend/src/pages/AdminFoodPage/components/AdminFoodList/AdminFoodList.jsx, frontend/src/pages/AdminFoodPage/components/AdminFoodUpdateForm/AdminFoodUpdateForm.jsx
공용 컴포넌트 몇가지 추가 및 어드민 푸드 페이지 통신을 제외한 기능들 채워넣었습니다. 
* 헤더와 네브바는 교체 예정이고, 화면 레이아웃이 잡히기 전에 제가 임시로 스타일링 한 것들이 있으므로 화면상 이상한 부분은 합쳐보고 추후 개선하겠습니다.
페이지네이션, 검색, 옵션에 따른 바텀시트 오픈 모두 로컬에서 정상 작동합니다
=> Feat/어드민페이지에 필요한 공용컴포넌트 추가

frontend/src/components/Admin/AdminTable/AdminTable.css, frontend/src/components/Admin/AdminTable/AdminTable.jsx, frontend/src/components/shared/FormInput/FormInput.css, frontend/src/components/shared/FormInput/FormInput.jsx, frontend/src/components/shared/Textarea/Textarea.jsx, frontend/src/pages/AdminExercisePage/AdminExercisePage.jsx, frontend/src/pages/AdminExercisePage/components/AdminExerciseAddForm/AdminExerciseAddForm.jsx, frontend/src/pages/AdminExercisePage/components/AdminExerciseDeleteForm/AdminExerciseDeleteForm.jsx, frontend/src/pages/AdminExercisePage/components/AdminExerciseList/AdminExerciseList.jsx, frontend/src/pages/AdminExercisePage/components/AdminExerciseUpdateForm/AdminExerciseUpdateForm.jsx, frontend/src/pages/AdminFeedPage/AdminFeedPage.jsx, frontend/src/pages/AdminFeedPage/components/AdminFeedAddForm/AdminFeedAddForm.jsx, frontend/src/pages/AdminFeedPage/components/AdminFeedDeleteForm/AdminFeedDeleteForm.jsx, frontend/src/pages/AdminFeedPage/components/AdminFeedList/AdminFeedList.jsx, frontend/src/pages/AdminFeedPage/components/AdminFeedUpdateForm/AdminFeedUpdateForm.jsx, frontend/src/pages/AdminFoodPage/components/AdminFoodAddForm/AdminFoodAddForm.jsx, frontend/src/pages/AdminFoodPage/components/AdminFoodUpdateForm/AdminFoodUpdateForm.jsx
어드민 exercise feed 페이지를 추가 했습니다.
feed 에 어드민 관리자여도 뭔가 유저가 작성한 글을 수정하는 권한을 주는게 맞나 싶어서 일단 빼놨습니다.
=> Feat/어드민 나머지 페이지 구현

backend/controllers/authController.js, frontend/package-lock.json, frontend/package.json, frontend/src/App.jsx, frontend/src/components/Layout/AllLayout/AppLayout.css, frontend/src/components/Layout/AllLayout/AppLayout.jsx, frontend/src/core/api/auth.js, frontend/src/core/hooks/useAuth.js, frontend/src/pages/DailyFoodPage/DailyFoodPage.css, frontend/src/pages/DailyFoodPage/DailyFoodPage.jsx, frontend/src/pages/DailyFoodPage/components/DailyFoodCalender/DailyFoodCalender.jsx, frontend/src/pages/DailyFoodPage/components/DailyFoodFeed/DailyFoodFeed.jsx, frontend/src/pages/LoginPage/LoginPage.jsx, frontend/src/routes/AppRouter.jsx
=> feat: AppLayout 제작

frontend/src/components/Layout/AdminLayout/AdminLayout.css, frontend/src/components/Layout/AdminLayout/AdminLayout.jsx, frontend/src/components/Layout/MainLayout/MainLayout.css, frontend/src/components/Layout/MainLayout/MainLayout.jsx
=> fix: 레이아웃 content scroll auto 만듦

frontend/src/components/shared/Header/Header.css, frontend/src/index.css
왜인지 잘 모르겠는데 헤더가 inline 으로 나오길래 wid 100% 로 줬습니다
=> fix: 헤더 스타일 잘 못됨

backend/.env, backend/app.js, frontend/.env, frontend/public/_redirects
브랜치 변경을 못해서 이 브랜치로 올립니다.
배포 테스트 중입니다.
=> feat: pubilc 폴더에 _redirects 파일 추가

frontend/src/components/shared/Button/Button.css, frontend/src/components/shared/Button/Button.jsx
=> feat: 버튼 컴포넌트 개발

frontend/src/components/shared/Tabs/Tabs.css
tab 스타일 수정 했습니다. 이제 안쪽 컨텐츠의 크기와 상관없이 균일하게 탭바의 크기가 결정됩니다
=> fix: tab 스타일 수정

frontend/src/components/Layout/MainLayout/MainLayout.jsx
=> Fix: MainLayout 오류 수정

frontend/src/utils/api.jsx
=> fix: LOCAL_BACKEND 환경변수로 수정

frontend/.gitignore
=> fix: .gitignore에 .env 추가

frontend/src/components/shared/Button/Button.css, frontend/src/components/shared/PendingButton/PendingButton.css, frontend/src/components/shared/PendingButton/PendingButton.jsx, frontend/src/pages/MainPage/MainPage.css
펜딩 버튼 추가했습니다. isLoading 이 true 라면 버튼 안에서 로딩스피너가 돕니다.
=> Feat/pending button 추가

backend/controllers/userController.js
내 정보 가져오기 userId로 정보 찾도록 수정했습니다.
=> fix: 내 정보 가져오기 userId로 정보 찾도록 수정

frontend/src/core/api/api.js
=> fix: LOCAL_BACKEND 환경변수로 변경

frontend/src/pages/WeightPage/WeightPage.css, frontend/src/pages/WeightPage/WeightPage.jsx, frontend/src/routes/AppRouter.jsx
=> feat: 웨이트 페이지 추가

backend/Model/DailyFood.js, backend/controllers/dailyFoodController.js, backend/routes/foodRouter.js, frontend/src/components/Layout/FoodLayout/FoodLayout.css, frontend/src/core/api/food.js, frontend/src/core/query/food.js, frontend/src/pages/DailyFoodPage/DailyFoodPage.jsx, frontend/src/pages/DailyFoodPage/components/DailyFoodFeed/DailyFoodFeed.jsx, frontend/src/pages/DailyFoodPage/components/DailyFoodSelectedFood/DailyFoodSelectedFood.jsx, frontend/src/pages/FoodSearchPage/FoodSearchPage.css, frontend/src/pages/FoodSearchPage/components/FoodSearchResultDetail.jsx
- DailyFood 페이지에서 바텀시트가 나오도록 기능 추가
- DailyFood 페이지 바텀 시트 css 추가
- DailyFood 수정 백엔드 및 api 추가
=> feat: dailyFood 수정 기능 추가

backend/controllers/dailyFoodController.js, frontend/src/core/api/food.js, frontend/src/core/query/food.js, frontend/src/pages/DailyFoodPage/DailyFoodPage.jsx, frontend/src/pages/DailyFoodPage/components/DailyFoodFeed/DailyFoodFeed.jsx, frontend/src/pages/FoodSearchPage/FoodSearchPage.jsx, frontend/src/pages/FoodSearchPage/components/FoodSearchResultDetail.jsx
- 추가한 음식이 삭제 가능하도록 기능을 추가 해 놓았습니다.
- 선택한 날짜에 맞게 음식이 추가되도록 만들어 놓았습니다.
=> feat: DailyFood delete function add

backend/Model/DailyExercise.js, backend/controllers/exerciseController.js, backend/routes/exerciseRouter.js, frontend/src/core/api/api.js, frontend/src/core/api/exercise.js, frontend/src/core/api/food.js, frontend/src/core/query/exercise.js, frontend/src/pages/DailyExercisePage/DailyExercisePage.jsx, frontend/src/pages/DailyExerciseSearchPage/DailyExerciseSearchPage.jsx, frontend/src/pages/DailyFoodPage/DailyFoodPage.jsx
=> feat: DailyExercise post backend

backend/routes/foodRouter.js, frontend/src/core/api/food.js, frontend/src/pages/DailyExerciseSearchPage/components/ExerciseSearchResult/ExerciseSearchResult.jsx
=> fix:DailyFood Router fix

frontend/src/core/api/food.js, frontend/src/pages/DailyFoodPage/DailyFoodPage.jsx
=> fix/api 버그 픽스

backend/controllers/dailyWeight.js, backend/routes/apiRouter.js, backend/routes/dailyWeightRouter.js, frontend/src/pages/DailyFoodPage/DailyFoodPage.jsx, frontend/src/pages/WeightPage/WeightPage.css, frontend/src/pages/WeightPage/WeightPage.jsx
=> feat: daily weight 작업중

backend/Model/User.js, backend/controllers/userController.js, frontend/src/pages/UserPage/UserPage.jsx
=> fix: User모델, UserPage수정

backend/controllers/feedController.js, backend/routes/feedRouter.js, frontend/src/core/api/feed.js, frontend/src/core/query/feed.js, frontend/src/pages/AdminFeedPage/components/AdminFeedList/AdminFeedList.jsx
feed 옵셔널하게 전부 가져오는 api 개발
예)
const { data } = useGetAllFeed({ page : 1 , q : '안녕', size : 10 })
== decription에 '안녕' 이 포함된 게시물 10개 1페이지 부분 출력
const { data } = useGetAllFeed()
== 조건 없이 피드 전체 출력
=> feat: feedAll api 추가

backend/controllers/feedController.js
feed all user id option 추가
예)
const { data } = useGetAllFeed({ page : 1 , q : '안녕', size : 10 })
== decription에 '안녕' 이 포함된 게시물 10개 1페이지 부분 출력
const { data } = useGetAllFeed()
== 조건 없이 피드 전체 출력
const { data } = useGetAllFeed({ userId : 67418c0e7711b62b73928bbc })
== 해당 유저 피드만 출력
=> feat: userId 로 필터 가능하게 변환

backend/controllers/exerciseController.js, backend/routes/exerciseRouter.js, frontend/src/core/api/exercise.js, frontend/src/core/query/exercise.js, frontend/src/pages/DailyExercisePage/DailyExercisePage.css, frontend/src/pages/DailyExercisePage/DailyExercisePage.jsx, frontend/src/pages/DailyExercisePage/DailyExerciseSelectedPage/DailyExerciseSelectedPage.jsx
- DailyExercise 삭제 기능을 추가하였습니다.
=> feat: DailyExercise delete function

frontend/src/pages/DailyExercisePage/DailyExercisePage.jsx, frontend/src/pages/DailyFoodPage/DailyFoodPage.jsx
식단에서 /food일 때 쿼리에 데이터가 안 불러져 오는 현상을 수정하였습니다.
=> fix: foodPage date missing fix

backend/Model/DailyWeight.js, backend/controllers/dailyWeight.js, backend/routes/dailyWeightRouter.js, frontend/src/core/api/dailyWeight.js, frontend/src/core/query/dailyWeight.js, frontend/src/core/utils/fn/dateParser.js, frontend/src/pages/WeightPage/WeightPage.css, frontend/src/pages/WeightPage/WeightPage.jsx, frontend/src/pages/WeightPage/components/WeightModal.jsx
feat: daily weight api 연결.
아직 bmi 계산은 못함
=> feat: daily weight api 연결

frontend/src/core/api/food.js, frontend/src/pages/AdminFeedPage/components/AdminFeedList/AdminFeedList.jsx, frontend/src/pages/DailyFoodPage/DailyFoodPage.jsx, frontend/src/pages/MainPage/MainPage.jsx, frontend/src/pages/WeightPage/WeightPage.jsx
=> feat: api 절반 연결

backend/controllers/feedController.js, frontend/src/pages/MainPage/MainPage.css, frontend/src/pages/MainPage/MainPage.jsx
=> feat: main api 연결 끝

backend/controllers/feedController.js, backend/controllers/userController.js, backend/routes/userRouter.js, frontend/src/core/api/user.js, frontend/src/core/query/user.js, frontend/src/pages/DailyFoodPage/components/DailyFoodFeed/DailyFoodFeed.jsx, frontend/src/pages/UserDetailPage/UserDetailPage.jsx, frontend/src/pages/UserDetailPage/css/UserDetailPage.css, frontend/src/pages/UserPage/UserPage.jsx
내정보에서 유저상세페이지 수정이 가능합니다. (이미지 제외)
=> feat: userDetail modify function add

frontend/src/pages/FeedDetailPage/FeedDetailPage.jsx, frontend/src/pages/UserPage/UserPage.css, frontend/src/pages/UserPage/UserPage.jsx, frontend/src/pages/UserPage/components/FeedContainer/FeedContainer.jsx
=> fix: UserPage 오류 수정

backend/controllers/userController.js, backend/utils/uploadFile.js, frontend/src/core/api/user.js
=> fix:userDetail img modify

backend/controllers/authController.js, backend/controllers/feedController.js, backend/controllers/userController.js, backend/routes/feedRouter.js, frontend/src/components/shared/PendingContainer/PendingContainer.css, frontend/src/components/shared/PendingContainer/PendingContainer.jsx, frontend/src/components/shared/SearchBar/SearchBar.jsx, frontend/src/pages/AdminExercisePage/components/AdminExerciseList/AdminExerciseList.jsx, frontend/src/pages/AdminFeedPage/components/AdminFeedList/AdminFeedList.jsx, frontend/src/pages/AdminFoodPage/components/AdminFoodList/AdminFoodList.jsx, frontend/src/pages/MainPage/MainPage.css, frontend/src/pages/MainPage/MainPage.jsx
feed delete api validation 해놓았고,
에러처리 메인페이지와 admin page 해놓았습니다
=> feat: 에러처리 및 api 개선

backend/controllers/feedController.js, backend/routes/feedRouter.js, frontend/src/core/api/feed.js, frontend/src/core/query/feed.js, frontend/src/pages/FeedPage/components/FeedBox/FeedBox.jsx
=> faet:registerView function

backend/app.js, frontend/src/pages/UserPage/UserPage.css, frontend/src/pages/UserPage/UserPage.jsx, frontend/src/pages/UserPage/components/FeedContainer/FeedContainer.css
=> fix: UserPage 수정

backend/app.js, backend/controllers/dailyFoodController.js, backend/controllers/foodController.js, backend/routes/foodRouter.js, frontend/src/core/api/food.js, frontend/src/core/query/food.js, frontend/src/pages/DailyExerciseSearchPage/DailyExerciseSearchPage.jsx, frontend/src/pages/DailyFoodPage/DailyFoodPage.css, frontend/src/pages/FoodSearchPage/FoodSearchPage.css, frontend/src/pages/FoodSearchPage/FoodSearchPage.jsx, frontend/src/pages/FoodSearchPage/components/FoodSearchResultDetail.jsx
- 음식 페이지 css 수정하였습니다. 
-- 달력 크기 조절, 총 영양소 배경색 넣기, "검색결과가 없습니다" 가운데 정렬, Tabs에서 g수 제거.
- 음식 검색을 하지 않았을 때, 전체 결과가 노출되도록 수정
=> fix:FoodPage css & FoodSearchPage searched list

frontend/src/App.jsx, frontend/src/pages/UserPage/UserPage.jsx
dev 파일과 합친 후 안쓰는 함수 수정 후 업로드 합니다.
=> feat:merge 수정

frontend/src/pages/WaterPage/WaterCalendar/WaterCalendar.css, frontend/src/pages/WaterPage/WaterCalendar/WaterCalendar.jsx, frontend/src/pages/WaterPage/WaterPage.css, frontend/src/pages/WaterPage/WaterPage.jsx
=> fix: WaterPage 수정

frontend/src/components/shared/Toast/Toast.css, frontend/src/components/shared/Toast/Toast.jsx, frontend/src/core/query/auth.js, frontend/src/core/query/dailyWeight.js, frontend/src/core/query/exercise.js, frontend/src/core/query/feed.js, frontend/src/core/query/food.js, frontend/src/core/query/user.js, frontend/src/pages/MainPage/MainPage.css, frontend/src/pages/MainPage/MainPage.jsx
토스트 전체적으로 적용하였고
메인 예외처리 조금 했습니다
=> feat: 토스트 전체적으로 적용

frontend/src/pages/FeedPage/components/FeedBox/FeedBox.jsx, frontend/src/pages/WaterPage/WaterCalendar/WaterCalendar.jsx
=> fix: feedPage error

frontend/src/pages/FoodSearchPage/components/FoodSearchResultDetail.jsx
=> fix: FoodPage error

frontend/src/pages/DailyFoodPage/components/DailyFoodFeed/DailyFoodFeed.jsx, frontend/src/pages/FoodSearchPage/components/FoodSearchResultDetail.jsx
데일리 푸드 페이지 수정
- 등록한 음식 뒤에 "개"추가
- placeholder 보이도록 초기값 0 제거
=> fix: FoodPage fix

frontend/src/pages/UserPage/UserPage.css
마이페이지에서 개인정보 수정 버튼의 색상 변경 완료하였습니다.
=> fix: myPage btn

frontend/src/pages/FeedDetailPage/components/FeedDetailBox.jsx
=> fix: FeedDetailPage error fix

frontend/src/pages/MainPage/MainPage.jsx
=> refactor: 메인페이지 칼로리 기준 변경

frontend/src/pages/MainPage/MainPage.jsx
=> refactor: 다시 수정

frontend/src/pages/FeedDetailPage/FeedDetailPage.jsx, frontend/src/pages/WaterPage/WaterCalendar/WaterCalendar.css
=> fix: feedDetail error

frontend/src/pages/DailyFoodPage/DailyFoodPage.jsx
=> fix: Mathfloor
